import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';
import { parseMap } from '../src/core.js';
import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url);
let chromium;
try { ({ chromium } = require('playwright')); }
catch {
  if (!process.env.PLAYWRIGHT_MODULE) throw new Error('Install Playwright: npm install --no-save playwright && npx playwright install chromium');
  ({ chromium } = require(process.env.PLAYWRIGHT_MODULE));
}
const base = process.env.TEST_FILE ? pathToFileURL(process.env.TEST_FILE).href : process.env.TEST_URL || 'http://127.0.0.1:5174';
const server = process.env.TEST_URL || process.env.TEST_FILE ? null : spawn(process.execPath, ['scripts/serve.mjs', '--dist', '--port', '5174'], { stdio: 'inherit' });
let browser;
try {
  for (let i = 0; server && i < 30; i++) {
    try { if ((await fetch(base)).ok) break; } catch {}
    await delay(100);
  }
  browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  await page.waitForLoadState('networkidle');
  await page.getByRole('heading', { name: 'КАРТЫ ArUco', exact: true }).waitFor();
  await page.evaluate(() => document.fonts.ready);
  assert.equal(await page.evaluate(() => document.fonts.check('600 24px Unbounded') && document.fonts.check('400 13px Inter')), true);
  assert.equal(await page.locator('#marker-rows tr').count(), 4);
  assert.equal(await page.locator('#map-preview [data-marker-id]').count(), 4);
  assert.match(await page.locator('footer').innerText(), /форк/);
  await page.getByRole('button', { name: 'Пример из исходника', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('#marker-rows tr').length === 13);
  assert.equal(await page.locator('#map-preview [data-marker-id]').count(), 13);
  await mkdir('test-results', { recursive: true });
  for (const format of ['SVG', 'PNG', 'TXT']) {
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: `Скачать ${format}`, exact: true }).click();
    const download = await downloadPromise;
    await download.saveAs(`test-results/map.${format.toLowerCase()}`);
  }
  const svg = await readFile('test-results/map.svg', 'utf8');
  assert.doesNotMatch(svg, /<pattern|<text|<line|<script/);
  assert.match(svg, /translate\(1707\.5 755\.5\)/);
  assert.equal(parseMap(await readFile('test-results/map.txt', 'utf8')).length, 13);
  const png = await readFile('test-results/map.png');
  assert.equal(png.readUInt32BE(16), 2000);
  assert.equal(png.readUInt32BE(20), 2000);
  await page.locator('#marker-rows input[data-field="length"]').first().fill('0');
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).isDisabled().then(disabled => assert.equal(disabled, true));
  assert.match(await page.locator('#validation-error').innerText(), /больше нуля/);
  await page.locator('#marker-rows input[data-field="length"]').first().fill('0.185');
  await page.getByRole('button', { name: 'Добавить маркер', exact: true }).click();
  assert.equal(await page.locator('#marker-rows tr').count(), 14);
  await page.getByRole('button', { name: 'Удалить маркер 0', exact: true }).click();
  assert.equal(await page.locator('#marker-rows tr').count(), 13);
  await page.getByRole('tab', { name: 'TXT' }).click();
  await page.getByLabel('Карта в формате TXT').fill('# header\n1 0.2 0.3 0.4 1 30 40 50');
  await page.getByRole('button', { name: 'Применить TXT', exact: true }).click();
  assert.equal(await page.locator('#map-preview [data-marker-id]').count(), 1);
  const txtPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Скачать TXT', exact: true }).click();
  const txtDownload = await txtPromise;
  assert.deepEqual(parseMap(await readFile(await txtDownload.path(), 'utf8')), [{ id: 1, length: .2, x: .3, y: .4, z: 1, rot_z: 30, rot_y: 40, rot_x: 50 }]);
  await page.getByLabel('Карта в формате TXT').fill('50 .1 0 0 0 0 0 0');
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).isDisabled().then(disabled => assert.equal(disabled, true));
  await page.getByRole('button', { name: 'Применить TXT', exact: true }).click();
  assert.match(await page.locator('#txt-error').innerText(), /Строка 1/);
  await page.locator('#file-input').setInputFiles({ name: 'custom.txt', mimeType: 'text/plain', buffer: Buffer.from('2 .24 -.25 .5 0 0 0 0') });
  await page.waitForFunction(() => document.querySelectorAll('#marker-rows tr').length === 1 && document.querySelector('#marker-rows input[data-field="id"]').value === '2');
  await page.getByLabel('Ширина поля, м').fill('1.2');
  assert.match(await page.locator('#canvas-dimensions').innerText(), /1200/);
  await page.getByLabel('Ширина поля, м').fill('');
  assert.equal(await page.getByRole('button', { name: 'Скачать PNG', exact: true }).isDisabled(), true);
  await page.getByLabel('Ширина поля, м').fill('2');
  await page.getByRole('button', { name: 'Новая карта', exact: true }).click();
  await page.getByLabel('Словарь меток').selectOption('DICT_5X5_100');
  assert.equal(await page.locator('#dictionary-select option').count(), 22);
  await page.getByLabel('Маркеров по ширине', { exact: true }).fill('3');
  await page.getByLabel('Маркеров по длине', { exact: true }).fill('2');
  await page.getByLabel('Размер маркера, м', { exact: true }).fill('0.1');
  await page.getByLabel('Начальный ID', { exact: true }).fill('90');
  await page.getByLabel('Конечный ID', { exact: true }).fill('99');
  await page.getByLabel('Крайние по ширине, м', { exact: true }).fill('0.8');
  await page.getByLabel('Крайние по длине, м', { exact: true }).fill('0.6');
  assert.equal(await page.locator('#marker-rows tr').count(), 6);
  assert.equal(await page.locator('#marker-rows input[data-field="id"]').last().inputValue(), '95');
  assert.equal(await page.locator('#marker-rows input[data-field="x"]').first().inputValue(), '-0.4');
  assert.equal(await page.locator('#marker-rows input[data-field="y"]').first().inputValue(), '0.3');
  await page.locator('#marker-rows input[data-field="x"]').first().fill('-0.35');
  await page.getByLabel('Между соседними', { exact: true }).check();
  assert.equal(await page.getByLabel('Шаг по ширине, м', { exact: true }).inputValue(), '0.4');
  assert.equal(await page.getByLabel('Шаг по длине, м', { exact: true }).inputValue(), '0.6');
  assert.equal(await page.locator('#marker-rows input[data-field="x"]').first().inputValue(), '-0.35');
  await page.getByRole('button', { name: 'Добавить маркер', exact: true }).click();
  assert.equal(await page.locator('#marker-rows tr').count(), 7);
  await page.getByLabel('Начальный ID', { exact: true }).fill('99');
  assert.equal(await page.locator('#marker-rows tr').count(), 7);
  assert.match(await page.locator('#grid-error').innerText(), /Не хватает ID/);
  await page.getByLabel('Начальный ID', { exact: true }).fill('90');
  assert.equal(await page.locator('#marker-rows tr').count(), 6);
  assert.equal(await page.getByRole('button', { name: 'Создать сетку', exact: true }).count(), 0);
  for (const format of ['SVG', 'PNG', 'TXT']) {
    const promise = page.waitForEvent('download');
    await page.getByRole('button', { name: `Скачать ${format}`, exact: true }).click();
    const download = await promise;
    await download.saveAs(`test-results/grid.${format.toLowerCase()}`);
  }
  const gridSvg = await readFile('test-results/grid.svg', 'utf8');
  assert.match(gridSvg, /width="2000mm" height="2000mm"/);
  assert.match(gridSvg, /DICT_5X5_100/);
  assert.equal(parseMap(await readFile('test-results/grid.txt', 'utf8'), 'DICT_5X5_100').length, 6);
  await page.getByLabel('Словарь меток').selectOption('DICT_4X4_50');
  assert.equal(await page.getByRole('button', { name: 'Скачать SVG', exact: true }).isDisabled(), true);
  assert.equal(await page.locator('#marker-rows tr').count(), 6);
  await page.locator('#file-input').setInputFiles('test-results/grid.txt');
  await page.waitForFunction(() => document.querySelector('#dictionary-select').value === 'DICT_5X5_100');
  assert.equal(await page.getByRole('button', { name: 'Скачать SVG', exact: true }).isEnabled(), true);
  assert.equal(await page.locator('#grid-error').isHidden(), true);
  await page.getByRole('tab', { name: 'TXT', exact: true }).click();
  const draft = await page.locator('#txt-source').inputValue() + '# черновик\n';
  await page.locator('#txt-source').fill(draft);
  await page.getByLabel('Шаг по ширине, м', { exact: true }).fill('0.5');
  assert.match(await page.locator('#grid-error').innerText(), /Сначала примените изменения TXT/);
  assert.equal(await page.locator('#txt-source').inputValue(), draft);
  assert.equal(await page.locator('#marker-rows tr').count(), 6);
  await page.getByRole('button', { name: 'Применить TXT', exact: true }).click();
  await page.getByLabel('Шаг по ширине, м', { exact: true }).fill('0.4');
  await page.getByRole('tab', { name: 'Таблица', exact: true }).click();
  await page.getByRole('button', { name: 'Включить тёмную тему', exact: true }).click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  assert.equal(await page.locator('#map-preview > svg > rect').first().getAttribute('fill'), 'white');
  const darkDownloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Скачать SVG', exact: true }).click();
  await (await darkDownloadPromise).saveAs('test-results/dark.svg');
  assert.equal(await readFile('test-results/dark.svg', 'utf8'), gridSvg);
  await page.screenshot({ path: 'test-results/dark.png', fullPage: true });
  await page.reload();
  await page.waitForLoadState('networkidle');
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  await page.getByRole('button', { name: 'Включить светлую тему', exact: true }).click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
  await page.getByLabel('Имя карты', { exact: true }).fill('Полигон.svg');
  for (const format of ['SVG', 'PNG', 'TXT']) {
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: `Скачать ${format}`, exact: true }).click();
    assert.equal((await downloadPromise).suggestedFilename(), `Полигон.${format.toLowerCase()}`);
  }
  await page.getByLabel('Шаг сетки X, м', { exact: true }).fill('0.2');
  await page.getByLabel('Шаг сетки Y, м', { exact: true }).fill('0.25');
  async function dragMarker(index, dx, dy) {
    const marker = await page.locator(`#map-preview [data-marker-index="${index}"]`).boundingBox();
    const sheet = await page.locator('#map-sheet').boundingBox();
    const x = marker.x + marker.width / 2, y = marker.y + marker.height / 2;
    await page.mouse.move(x, y);
    await page.mouse.down();
    await page.mouse.move(x + dx / 2 * sheet.width, y - dy / 2 * sheet.height, { steps: 5 });
    await page.mouse.up();
  }
  await dragMarker(0, .22, -.19);
  assert.equal(await page.locator('#marker-rows input[data-field="x"]').first().inputValue(), '-0.2');
  assert.equal(await page.locator('#marker-rows input[data-field="y"]').first().inputValue(), '0.25');
  assert.equal(parseMap(await page.locator('#txt-source').inputValue())[0].x, -.2);
  await page.locator('#map-preview [data-marker-index="0"]').press('ArrowRight');
  assert.equal(await page.locator('#marker-rows input[data-field="x"]').first().inputValue(), '0');
  await page.getByLabel('Привязка к сетке', { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Увеличить масштаб просмотра', exact: true }).click();
  await dragMarker(0, .07, .03);
  assert.ok(Math.abs(Number(await page.locator('#marker-rows input[data-field="x"]').first().inputValue()) - .07) < .00001);
  assert.ok(Math.abs(Number(await page.locator('#marker-rows input[data-field="y"]').first().inputValue()) - .28) < .00001);
  const beforeCancel = await page.locator('#txt-source').inputValue();
  const markerBox = await page.locator('#map-preview [data-marker-index="0"]').boundingBox();
  await page.mouse.move(markerBox.x + markerBox.width / 2, markerBox.y + markerBox.height / 2);
  await page.mouse.down();
  await page.mouse.move(markerBox.x + markerBox.width / 2 + 30, markerBox.y + markerBox.height / 2 + 20, { steps: 3 });
  await page.keyboard.press('Escape');
  await page.mouse.up();
  assert.equal(await page.locator('#txt-source').inputValue(), beforeCancel);
  await page.getByLabel('Привязка к сетке', { exact: true }).check();
  await page.getByLabel('Шаг сетки X, м', { exact: true }).fill('');
  assert.equal(await page.locator('#placement-error').isVisible(), true);
  assert.equal(await page.locator('#txt-source').inputValue(), beforeCancel);
  await page.getByLabel('Шаг сетки X, м', { exact: true }).fill('0.2');
  assert.equal(await page.locator('#placement-error').isHidden(), true);
  await page.getByRole('button', { name: 'Вписать', exact: true }).click();
  await page.locator('#file-input').setInputFiles({ name: 'duplicates.txt', mimeType: 'text/plain', buffer: Buffer.from('1 .185 -.4 .4 0 0 0 0\n1 .185 .4 -.4 0 0 0 0') });
  await page.waitForFunction(() => document.querySelectorAll('#marker-rows tr').length === 2);
  assert.equal(await page.getByLabel('Имя карты', { exact: true }).inputValue(), 'duplicates');
  await dragMarker(1, -.21, .17);
  assert.equal(await page.locator('#marker-rows input[data-field="x"]').first().inputValue(), '-0.4');
  assert.equal(await page.locator('#marker-rows input[data-field="x"]').nth(1).inputValue(), '0.2');
  assert.equal(await page.locator('#marker-rows input[data-field="y"]').nth(1).inputValue(), '-0.25');
  await dragMarker(1, 10, -10);
  assert.equal(await page.locator('#marker-rows input[data-field="x"]').nth(1).inputValue(), '0.8');
  assert.equal(await page.locator('#marker-rows input[data-field="y"]').nth(1).inputValue(), '-0.75');
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  const touchPage = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
  touchPage.on('pageerror', error => errors.push(error.message));
  await touchPage.goto(base);
  await touchPage.waitForLoadState('networkidle');
  await touchPage.locator('#map-preview [data-marker-index="0"]').scrollIntoViewIfNeeded();
  const touchMarker = await touchPage.locator('#map-preview [data-marker-index="0"]').boundingBox();
  const touchSheet = await touchPage.locator('#map-sheet').boundingBox();
  const touchClient = await touchPage.context().newCDPSession(touchPage);
  const tx = touchMarker.x + touchMarker.width / 2, ty = touchMarker.y + touchMarker.height / 2;
  await touchClient.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: tx, y: ty }] });
  await touchClient.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: tx + touchSheet.width * .1, y: ty + touchSheet.height * .1 }] });
  await touchClient.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  assert.equal(await touchPage.locator('#marker-rows input[data-field="x"]').first().inputValue(), '-0.2');
  assert.equal(await touchPage.locator('#marker-rows input[data-field="y"]').first().inputValue(), '0.2');
  await touchPage.close();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: example, import, editing, 22 dictionaries, live grid, protected TXT drafts, center-spacing modes, persistent dark theme, white exports, physical SVG, PNG/TXT, validation, named downloads, snapped/free pointer drag, zoom, keyboard movement, duplicate IDs, cancellation, mobile touch drag, mobile layout.');
} finally {
  await browser?.close();
  server?.kill();
}
